### ISSUE TITLE
In core/images.md comment paths for newbs like me

### ISSUE THREAD

**Issue by croepha** [CanonicalLtd/snappy-docs#15]
So I was trying to follow the directions for setting up 
core/images.md

and i was working in a network mounted directory and snap was complaining about not being able to find the files.  as a work around I was able to bind mount the place in my home directory and then it worked... should add a comment so that the un-initated would know that you have to be careful about which directory you are working in, and that it might not be available when using snap commands

Thanks

**Comment by caldav** [comment]
The core.images page has been moved to https://docs.ubuntu.com/core/en/guides/build-device/image-building.

Source of the doc being https://github.com/CanonicalLtd/ubuntu-core-docs/blob/master/en/guides/build-device/image-building.md
