### ISSUE TITLE
The examples link on http://snapcraft.io/docs/reference/plugins/dump is broken.

### ISSUE THREAD

**Issue by nottrobin** [CanonicalLtd/snappy-docs#18]
_From @nturner on October 25, 2016 20:46_
## Summary

The examples link on http://snapcraft.io/docs/reference/plugins/dump is broken.
## Process

Go to http://snapcraft.io/docs/reference/plugins/dump and click on Examples
## Current and expected result

I'd expect some cool examples. Instead, I see an error page.

_Copied from original issue: ubuntudesign/snapcraft.io#213_

**Comment by nottrobin** [comment]
Thanks @nturner.

It seems the examples links, which are just searches on GitHub (e.g. https://github.com/search?o=desc&q=filename%3Asnapcraft.yaml+%22plugin%3A+dump%22+&s=indexed&type=Code&utf8=%E2%9C%93), only work if you're logged in. Because otherwise they need "at least one user, organization, or repository" in the search.

@caldav would you be able to work out the best solution here?

**Comment by caldav** [comment]
No good solution here, except making the link more specific and adding examples to the page itself. Closing this bug because an example has been added, opening a new one for all the Examples links.
