### ISSUE TITLE
snapcraft tour commands output does not match reality

### ISSUE THREAD

**Issue by axinojolais** [CanonicalLtd/snappy-docs#19]
Hi,

I just took the tour with yakkety, and the output in the doc does not match reality. For example, I get the following, which is not what the doc says : 

```
% sudo snap install --force-dangerous hello-world-service_0.1_*.snap
error: cannot perform the following tasks:
- Mount snap "hello-world-service" (unset) (snap "hello-world-service" requires devmode or confinement override)
```

Also, `snap install` does not display the name, version, author etc.. of the snap

**Comment by caldav** [comment]
This is fixed by https://github.com/ubuntudesign/snapcraft.io/pull/236
