### ISSUE TITLE
http://snapcraft.io/docs/core/usage, Developer mode is not so prompting as documented

### ISSUE THREAD

**Issue by ycheng** [CanonicalLtd/snappy-docs#22]
per http://snapcraft.io/docs/core/usage

in Developer mode, it said the snap will prompt something like

"Error: this version of foo requires devmode."

but in snapd 2.16+16.10ubuntu1.2, now it's

$ snap install classic --beta
error: cannot install "classic": snap not found

is it a design change or a bug in snapd ?

**Comment by caldav** [comment]
You are right, I think it's a design change. I'll check.
