### ISSUE TITLE
Debian install page should be clearer about supported versions

### ISSUE THREAD

**Issue by popey** [CanonicalLtd/snappy-docs#55]
The page https://snapcraft.io/docs/core/install-debian explains briefly how to install on debian, but isn't quite clear on which version number / codename is supported. In addition it doesn't explicitly exclude (should it?) raspbian, as some expect debian == rasbian and believe it should be available.

**Comment by aycgit** [comment]
agree, i had this problem and since raspian is based on debian it should atleast say that it doesn't work
