### ISSUE TITLE
Add solus logo to the snapcraft home page

### ISSUE THREAD

**Issue by popey** [CanonicalLtd/snappy-docs#90]
Solus is now a snap supported system (out of the box) so we should add their distro logo to the home page along with the other supported distros.

The branding can be found at https://solus-project.com/branding/

**Comment by evandandrea** [comment]
Re-filing on https://github.com/canonical-websites/snapcraft.io/issues

**Comment by evandandrea** [comment]
Filed as https://github.com/canonical-websites/snapcraft.io/issues/358
