### ISSUE TITLE
Add solus snap install instructions

### ISSUE THREAD

**Issue by popey** [CanonicalLtd/snappy-docs#91]
The install page should add Solus which is now a supported distribution.

https://snapcraft.io/docs/core/install

Solus now ships snapd by default. The install page should make this known.

**Comment by ikeydoherty** [comment]
If it helps any:

```
# Always ensure you're up to date before installing new packages
sudo eopkg up 
sudo eopkg install snapd

# Reboot now to ensure AppArmor and snapd are initialized at boot
sudo reboot
```
